### ISSUE TITLE
need some explaination for the WorldOffsetX,WorldOffsetZ config

### ISSUE THREAD

**Issue by laughxing** [metaworking/channeld#40]
hi, I want to setup a test for channeld, but got some error.  it's quite frustating to understand the sptial config.
from the code
``` 
	// In the left-handed coordinate system, the difference between the world origin and the top-right corner of the first grid, in the simulation/engine units.
	// This is how we uses the offset value to calculate which grid a (x,z) point is in: gridX = Floor((x - OffsetX) / GridWidth), gridY = Floor((y - OffsetY) / GridHeight)
	// If the world origin is exactly in the middle of the world, the offset should be (-WorldWidth*0.5, -WorldHeight*0.5).
	WorldOffsetX float64
	WorldOffsetZ float64
``` 

why it's the top-right corner of the first grid? it seems that the ctl.WorldOffsetX/Y is used as the min limit for the X/Y coordinate value.

**Comment by indiest** [comment]
The description is wrong - it should be the ***bottom-left*** corner of the first grid.

This is an example of the world origin in the middle of the world:

![spatial-config drawio](https://github.com/metaworking/channeld/assets/5010912/1eb13ada-c60c-495b-addd-f964d6adbf36)

**Comment by laughxing** [comment]
thanks for the detailed graph!
